# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FQfg8B28soxNyidra0YzGoYDiyaljwr
"""

!pip install openai

import streamlit as st

with open("/content/Arabic/Arabic_Lesson-3-4.txt", encoding="utf-8") as f:
    arabic_text = f.read()
st.session_state["arabic_text"] = arabic_text

st.chat_input("Ask me anything about Arabic lessons")